# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 15:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='birthdate',
            field=models.DateField(default=datetime.datetime(2015, 12, 23, 15, 29, 41, 452349, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
